### ISSUE TITLE
Response example in dark mode is very hard to read.

### ISSUE THREAD

**Issue by CodeSchwert** [immutable/imx-docs#9]
### Are you sure it's a bug?

- [X] Yes, it looks like a bug

### Is there an existing issue for this bug?

- [X] I have searched existing issues, and this bug hasn't been reported yet

### Issue description

The API response example is very hard to read due to the font colour being very close to the background colour! (Dark mode only)

![image](https://user-images.githubusercontent.com/2661899/171348380-be9e439a-49d4-49a1-b026-608290b2f818.png)

**Comment by ckailash** [comment]
This is now fixed.
